name: Trigger Sonar analysis

on:
  workflow_run:
    workflows:
      - Build project
    types:
      - completed

concurrency:
  group: trigger-sonar-${{ github.event.workflow_run.head_branch }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  prepare:
    if: github.event.workflow_run.conclusion == 'success'
    uses: WrenSecurity/.github/.github/workflows/sonar-prepare.yml@main
    name: Prepare analysis context
    with:
      workflow_run: ${{ toJSON(github.event.workflow_run) }}
  trigger:
    needs: prepare
    if: needs.prepare.outputs.sonar_allowed
    name: Trigger Sonar analysis
    uses: adela-domokosova/.github/.github/workflows/sonar-maven.yml@fix-analysis-checkout
    with:
      commit_sha: ${{ github.event.workflow_run.head_sha }}
      java_version: 17
      project_key: 'adela-domokosova_wrenidm'
      pull_request: ${{ needs.prepare.outputs.pull_request }}
    secrets:
      sonar_token: ${{ secrets.SONAR_TOKEN }}
